config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    post 'join', on: :member
    delete 'leave', on: :member
  end
  resources :seasons do
    post 'generate_schedule', on: :member
  end
  resources :leagues
  resources :matches do
    post 'select', on: :member
    post 'confirm_selection', on: :member
  end
  devise_for :players, controllers: {
    sessions: 'player/sessions',
    registrations: 'player/registrations'
  }
  root 'pages#home'

end

app/models/season.rb
class Season < ApplicationRecord
    has_many :matches
    has_many :teams
    has_and_belongs_to_many :leagues, dependent: :destroy


    def generate_schedule
        teams = Team.all.to_a
        num_teams = teams.length
    
        # Ensure that the number of teams is even for the round-robin algorithm
        if num_teams.odd?
          teams << nil
          num_teams += 1
        end
    
        num_rounds = num_teams - 1
    
        (1..num_rounds).each do |round|
          matches = []
    
          teams.shuffle.each_slice(2) do |pair|
            matches << pair
          end
    
          matches.each do |pair|
            Match.create(team_one_id: pair[0]&.id, team_two_id: pair[1]&.id, season_id: self.id)
          end
    
          teams.rotate!(-1) # Rotate teams for the next round
        end
    end

end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :set_season, only: %i[ show edit update destroy ]

  # GET /seasons or /seasons.json
  def index
    @seasons = Season.all
  end

  # GET /seasons/1 or /seasons/1.json
  def show
    @season = Season.find(params[:id])
    @teams = @season.teams
    @leagues = @season.leagues

    current_date = Date.today
    @current_season = Season.where("start_date <= ? AND end_date >= ?", current_date, current_date).first
    
  end

  # GET /seasons/new
  def new
    @season = Season.new
  end

  # GET /seasons/1/edit
  def edit
    @season = Season.find(params[:id])
    @leagues = League.all
  end

  # POST /seasons or /seasons.json
  def create
    @season = Season.new(season_params)

    respond_to do |format|
      if @season.save
        format.html { redirect_to season_url(@season), notice: "Season was successfully created." }
        format.json { render :show, status: :created, location: @season }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seasons/1 or /seasons/1.json
  def update
    @season = Season.find(params[:id])
    
    respond_to do |format|
      if @season.update(season_params)
        format.html { redirect_to season_url(@season), notice: "Season was successfully updated." }
        format.json { render :show, status: :ok, location: @season }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seasons/1 or /seasons/1.json
  def destroy
    @season.destroy

    respond_to do |format|
      format.html { redirect_to seasons_url, notice: "Season was successfully destroyed." }
      format.json { head :no_content }
    end
  end 

  def generate_schedule
    @season = Season.find(params[:id])
    @season.generate_schedule
    redirect_to @season, notice: 'Schedule generated successfully!'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_season
      @season = Season.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def season_params
      params.require(:season).permit(:name, :start_date, :end_date, league_ids: [] )
    end
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/views/seasons/_form.html.erb
<%= simple_form_for(@season) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.collection_select :league_ids, League.all, :id, :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/seasons/_season.html.erb
<div id="<%= dom_id season %>">
  <p>
    <strong>Name:</strong>
    <%= season.name %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= season.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= season.end_date %>
  </p>

</div>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render "form", season: @season %>

<br>

<div>
  <%= link_to "Show this season", @season %> |
  <%= link_to "Back to seasons", seasons_path %>
</div>

app/views/seasons/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Seasons</h1>

<div id="seasons">
  <% @seasons.each do |season| %>
    <%= render season %>
    <p>
      <%= link_to "Show this season", season %>
    </p>
  <% end %>
</div>

<%= link_to "New season", new_season_path %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render "form", season: @season %>

<br>

<div>
  <%= link_to "Back to seasons", seasons_path %>
</div>

app/views/seasons/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @season %>
<h4>Teams:</h4>

<% @teams.each do |team| %>
  <h5><%= team.name %></h5>
<% end %>
<!--
<h5>Leagues:</h5>
<ul>
  <% @leagues.each do |league| %>
    <li><%= league.name %></li>
  <% end %>
</ul>
-->
<div>
  <%= link_to "Edit this season", edit_season_path(@season) %> |
  <%= link_to "Back to seasons", seasons_path %>

  <%= button_to "Destroy this season", @season, method: :delete %>
</div>
<% if current_player.admin? %> <!-- Assuming admin can generate schedule -->
  <%= button_to "Generate Schedule", generate_schedule_season_path(@season), method: :post, class: "btn btn-primary" %>
<% end %>