config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    post 'join', on: :member
    delete 'leave', on: :member
  end
  resources :seasons do
    post 'generate_schedule', on: :member
  end
  resources :leagues
  resources :matches do
    post 'select', on: :member
    post 'confirm_selection', on: :member
  end
  devise_for :players, controllers: {
    sessions: 'player/sessions',
    registrations: 'player/registrations'
  }
  root 'pages#home'

end

app/models/league.rb
class League < ApplicationRecord
    has_many :teams
    has_and_belongs_to_many :seasons

end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: %i[ show edit update destroy ]

  # GET /leagues or /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1 or /leagues/1.json
  def show
    @league = League.find(params[:id])
    @seasons = @league.seasons

    
  end

  # GET /leagues/new
  def new
    @league = League.new
    @seasons = Season.all
    @current_season = determine_current_season
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues or /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to league_url(@league), notice: "League was successfully created." }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1 or /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to league_url(@league), notice: "League was successfully updated." }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1 or /leagues/1.json
  def destroy
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url, notice: "League was successfully destroyed." }
      format.json { head :no_content }
    end
  end  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    def determine_current_season
      @seasons.each do |season|
        return season if Date.today.between?(season.start_date, season.end_date)
      end
      nil
    end

    # Only allow a list of trusted parameters through.
    def league_params
      params.require(:league).permit(:name, season_ids: [] )
    end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= simple_form_for(@league) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.collection_select :season_ids, [@current_season].compact, :id, :name, {}, { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/leagues/_league.html.erb
<div id="<%= dom_id league %>">
  <p>
    <strong>Name:</strong>
    <%= league.name %>
  </p>

</div>

app/views/leagues/edit.html.erb
<h1>Editing league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Show this league", @league %> |
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Leagues</h1>

<div id="leagues">
  <% @leagues.each do |league| %>
    <%= render league %>
    <p>
      <%= link_to "Show this league", league %>
    </p>
  <% end %>
</div>

<%= link_to "New league", new_league_path %>

app/views/leagues/new.html.erb
<h1>New league</h1>

<%= render "form", league: @league %>

<br>

<div>
  <%= link_to "Back to leagues", leagues_path %>
</div>

app/views/leagues/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @league %>
<p>Teams:</p>
<ul>
  <% @league.teams.each do |team| %>
    <li><%= team.name %></li>
  <% end %>
</ul>
<p>Seasons:</p>
<ul>
<% @league.season_ids.each do |season_id| %>
  <li><%= Season.find(season_id).name %></li>
<% end %>
</ul>
<div>
  <%= link_to "Edit this league", edit_league_path(@league) %> |
  <%= link_to "Back to leagues", leagues_path %>

  <%= button_to "Destroy this league", @league, method: :delete %>
</div>