config/routes.rb
Rails.application.routes.draw do
  resources :teams do
    post 'join', on: :member
    delete 'leave', on: :member
  end
  resources :seasons do
    post 'generate_schedule', on: :member
  end
  resources :leagues
  resources :matches do
    post 'select', on: :member
    post 'confirm_selection', on: :member
  end
  devise_for :players, controllers: {
    sessions: 'player/sessions',
    registrations: 'player/registrations'
  }
  root 'pages#home'

end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Template</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Teams', teams_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Leagues', leagues_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Seasons', seasons_path, class:"nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
      <li class="nav-item dropdown">
      <% if signed_in? %>
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= current_player.name %>
        </a>
        <ul class="dropdown-menu dropdown-menu-md-end">
        <li><%= link_to 'Edit Account', edit_player_registration_path, class:"dropdown-item" %></li>
        <li><%= button_to "Log out", destroy_player_session_path, method: :delete, data: { turbo: "false" }, class:"dropdown-item" %></li>
      <% else %>
          <li><%= link_to "Log in", new_player_session_path, class:" nav-link btn btn-info btn-sm" %></li>          
          <li><%= link_to "Register", new_player_registration_path, class:" nav-link btn btn-primary btn-sm" %></li>
        </ul>
      <% end %>
      </ul>
      </li>
    </div>
  </div>
</nav>